services:

  db:
    image: postgres:16-alpine
    container_name: api-culteur-db
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql #enlever en prod
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db_api_culteur
      POSTGRES_USER: postgres
    networks:
      - api-culteur-network
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_api_culteur", "-U", "postgres"]
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  db_data:
    name: api_culteur_db_data
    
networks:
  api-culteur-network:
    name: api-culteur-network